buku/urls.py
from django.urls import path
from . import views

app_name="buku"

urlpatterns = [
    path('',views.index,name="index"),
    path('add/', views.add, name='add'),
    path('likes/<str:id>', views.likes, name="likes"),
    path('top5/', views.top5, name="top5")
]

luhalu/urls.py
from django.urls import path
from . import views

app_name = "luhalu"

urlpatterns = [
    path('',views.index,name='index'),
    path('register/',views.register, name='register'),
    path('login/',views.user_login, name='user_login'),
    path('logout/',views.user_logout, name='logout'),
]

story9/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('buku.urls')),
    path('luhalu/',include('luhalu.urls')),
]

buku/models.py
from django.db import models

# Create your models here.
class Library(models.Model):
    nama = models.CharField('nama',max_length=3000)
    id_buku = models.CharField('id_buku',max_length=3000, default="AAAAAAAAAAAA")
    likes = models.PositiveIntegerField(default=0)

luhalu/models.py
from django.db import models

# Create your models here.

buku/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .models import Library
import json


# Create your views here.
def index(request):
    return render(request,'index.html')

@csrf_exempt
def add(request):
    if request.method == "POST":
        contain = request.POST["id_buku"]
        obj = Library.objects.all().filter(id_buku__icontains= contain).count()
        if obj == 0:
            Library.objects.create(nama = request.POST["nama"], id_buku = request.POST["id_buku"])
    return redirect("buku:index")

@csrf_exempt
def likes(request,id):
    try:
        book_like = Library.objects.get(id_buku=id)
        book_like.likes +=1
        book_like.save()
        return JsonResponse({'likes':book_like.likes})
    except:
        return JsonResponse({'likes':0})

def top5(request):
    return JsonResponse({'semua_buku':list(Library.objects.all().order_by('-likes')[:5].values())})

luhalu/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def index(request):
    return render(request,'indexs.html')

def register(request):
    form = UserCreationForm()
    context = {
        'form': form,
    }
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('luhalu:user_login')
        else :
            context.update({'pesan':'invalid request, terdapat kesalahan'})      
    return render(request,'register.html',context=context)


def user_login(request):
    if request.method == "POST":
        userr = request.POST['username']
        passw = request.POST['password']
        user = authenticate(request, username=userr, password=passw)
        if user != None:
            login(request, user)
            return redirect('luhalu:index')
        else:
            context = {
                'pesan':'invalid request, akun tidak terdaftar'
            }
            return render(request, 'login.html', context=context)
    return render(request, 'login.html')

def user_logout(request):
    request.session.flush()
    logout(request)
    return redirect('luhalu:index')

buku/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="untukurl" content="{% url 'buku:add' %}">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container mt-5 ">
        <div class="d-flex flex justify-content-center mb-5 mt-5">
            <h1><i>Silahkan cari buku disini, yang buat udah capek gayn</i></h1>
        </div>
        <div class="d-flex flex column">
            <input type="text" class="form-control" name="search" placeholder="Cari buku disini :( !">
            <button class="btn btn-dark" id="find">Ayo</button>
        </div>
        <div class="d-flex flex justify-content-center">
            <button type="button" class="modal-like btn btn-dark" data-toggle="modal" data-target="#exampleModalCenter">
                Top 5 gayn 
            </button>
        </div>
        <div class="mt-5">
            <table class="table">
                <thead class="thead-dark">
                  <tr>
                    <th scope="col" style="width: 20%;">Cover</th>
                    <th scope="col" style="width: 30%;">Judul</th>
                    <th scope="col" style="width: 20%;">Penulis</th>
                    <th scope="col" style="width: 25%;">Tahun Publikasi</th>
                    <th scope="col" style="width: 40%;">Like</th>
                  </tr>
                </thead>
                <tbody>
                    
                </tbody>
            </table>
        </div>
    </div>
    <!-- Modal -->
  <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Top 5</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-dark" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

<script src="{% static 'scripts.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
</html>

luhalu/templates/indexs.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style1.css' %}">
    <title>Io</title>
</head>
<body>
    <div class="container  column">
        {% if user.is_authenticated %}
        <div class="authenticated column">
            <div class="nama_user">
                <h1>HI, Welcome {{ request.user }}</h1>
            </div>
            <div class="logout-but">
                <a href="{% url 'luhalu:logout'%}"><button id="logout-but"class="btn btn-dark">Capek Gan? LogOut SKUT</button></a>
            </div>
        </div>
        {% else %}

        <div class="not-authenticated">
            <div class="">
                <h1>Hai ganteng</h1>  
            </div>
            <div>
                <a href=" {% url 'luhalu:register' %}">
                    <button class="reg-but btn btn-dark mr-2">Daftar</button>
                </a>
                <a href=" {% url 'luhalu:user_login' %}">
                    <button class="login-but btn btn-dark">Login</button>
                </a>                
            </div>
 
        </div>
        {% endif %}
    </div>




    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

luhalu/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style1.css' %}">
    <title>Io</title>
</head>
<body>
    <div class="container d-flex flex justify-content-center column">
        
        <div class="mt-5 mb-5">
            <div class="title-greet ultra-center">
                <p>Ayo Login!</p>
            </div>
            <div class="error">
                {% if pesan != None %}
                <h3><i>* {{ pesan }} </i></h3>
            </div>
            
    
            {% endif %}
            <form method="POST" action="{% url 'luhalu:user_login' %}">
                {% csrf_token %}
                <h3>Username:</h3>
                <input type='text' class="form-control" id="username" name="username" placeholder="Username">
                <h3>Password:</h3>
                <input type='password' class="form-control" id="password" name="password" placeholder="Password">
                <div class="d-flex flex justify-content-center mt-2">
                    <button class="log-buty btn btn-dark">Masuk Gan</button>
                </div>
            </form>
            <div class="title-greet mt-5 ultra-center"> 
                <a href="{% url 'luhalu:register' %}"><button class="btn btn-dark">Belum punya akun?</button></a>
            </div>
        </div>
    </div>

</body>
</html>

luhalu/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style1.css' %}">
    <title>Io</title>
</head>
<body>
    <div class="container ultra-center">    
        <h4>Bikin akun skooottt!</h4>
        <div class="gabut"></div>
        {% if pesan != None %}
        <h3><i>* {{ pesan }} </i></h3>

        {% endif %}
        <form method="POST">
            {% csrf_token %}
            {{ form.as_table }}
            <input class="reg-bro btn btn-light" type="submit" value="Daftar!">
        </form>

        <div>
            <a href="{% url 'luhalu:user_login' %}"><button class="btn btn-dark">Udah Punya? SKut login</button></a>
        </div>
    </div>
    
</body>
</html>